const assert = require("node:assert/strict");
const os = require("node:os");
const path = require("node:path");
process.env.EVENT_DB_PATH = path.join(os.tmpdir(), `diagnostic-fixes-${process.pid}.sqlite`);
process.env.EVENT_STORE_MODE = "local";
delete process.env.KV_REST_API_URL;
delete process.env.KV_REST_API_TOKEN;
const store = require("../event-store");
const submissions = require("../submission-store");
const reports = require("../report-store");
const { applyEventQueryFilters } = require("../event-query");
const { publicEvent } = require("../api/events");
const { readAllPages } = require("../supabase-pagination");

(async () => {
  await store.setCachedEvents([{ id: "legacy-news", title: "原有新聞" }]);
  const created = await Promise.all(Array.from({ length: 20 }, (_, index) => submissions.createSubmission({ title: `投稿 ${index}`, description: "道路中斷", category: "traffic", latitude: 25, longitude: 121 })));
  assert.equal((await submissions.listSubmissions()).length, 20, "concurrent submissions must survive");
  const submissionId = created[0].submissionId;
  await submissions.updateSubmission(submissionId, { status: "approved" });
  assert.ok((await store.getOfficialEvents()).some(item => item.id === "legacy-news"), "first publication preserves pre-migration cache");
  let event = (await store.getOfficialEvents()).find(item => item.submissionId === submissionId);
  assert.ok(event.publishedAt && event.occurredAt);
  await submissions.updateSubmission(submissionId, { status: "rejected" });
  assert.equal((await store.getOfficialEvents()).some(item => item.submissionId === submissionId), false);
  assert.equal((await store.getDurableValue(store.OFFICIAL_EVENTS_KEY)).some(item => item.submissionId === submissionId), false);
  await submissions.updateSubmission(submissionId, { status: "approved", category: "activity", eventStartTime: new Date().toISOString(), eventEndTime: new Date(Date.now() + 3600000).toISOString() });
  event = (await store.getOfficialEvents()).find(item => item.submissionId === submissionId);
  assert.equal(event.eventKind, "activity"); assert.ok(event.startsAt && event.endsAt);
  const submissionApi = require("../api/submission");
  assert.equal(submissionApi.normalizeSubmissionTime("2026-10-06T12:00"), "2026-10-06T04:00:00.000Z");
  assert.equal(submissionApi.automaticExpiration({ category: "activity", eventStartTime: "2026-10-06T04:00:00.000Z" }), "2026-10-07T10:00:00.000Z");
  await submissions.updateSubmission(submissionId, { hiddenByReports: true });
  assert.equal((await store.getOfficialEvents()).some(item => item.submissionId === submissionId), false);
  await submissions.updateSubmission(submissionId, { hiddenByReports: false, expirationTime: new Date(Date.now() - 1000).toISOString() });
  assert.equal((await store.getOfficialEvents()).some(item => item.submissionId === submissionId), false);
  assert.equal((await submissions.listSubmissions()).find(item => item.submissionId === submissionId).status, "expired");
  await Promise.all(Array.from({ length: 20 }, (_, index) => reports.createReport({ eventId: "event", message: String(index) })));
  assert.equal((await reports.getReports()).length, 20);
  const rows = [{ city: "臺北市", title: "臺灣展覽", sourceName: "文化局" }];
  assert.equal(applyEventQueryFilters(rows, { city: "台北", q: "台灣" }).length, 1);
  const projected = publicEvent({ sourceTrace: [{ outlet: "政府", title: "公告", url: "https://example.test", rawSourceData: "private" }], severity: "high", verifiedStatus: "verified", reviewState: "approved", contactInfo: "private" });
  assert.equal(projected.sourceTrace[0].outlet, "政府"); assert.equal(projected.severity, "high"); assert.equal(projected.contactInfo, undefined); assert.equal(projected.sourceTrace[0].rawSourceData, undefined);
  const data = Array.from({ length: 1201 }, (_, id) => ({ id }));
  const paged = await readAllPages(() => ({ range: async (from, to) => ({ data: data.slice(from, to + 1), count: data.length }) }));
  assert.equal(paged.length, 1201);
  await assert.rejects(() => readAllPages(() => ({ range: async () => ({ data: [], count: 1001 }) })), /Incomplete/);
  const { isEventInBounds } = await import("../assets/index/modules/map-bounds-filter.mjs");
  const bounds = { west: -1, east: 1, south: -1, north: 1 };
  for (const value of [null, undefined, "", " ", false]) assert.equal(isEventInBounds({ lat: value, lng: value }, bounds), false);
  assert.equal(isEventInBounds({ lat: 0, lng: 0 }, bounds), true);
  const workflow = require("node:fs").readFileSync(path.join(__dirname, "../.github/workflows/preview-smoke-test.yml"), "utf8");
  const pattern = workflow.match(/&& (\/\^.*\$\/)\.test\(hostname\)/)[1];
  const hostnamePattern = new RegExp(pattern.slice(1, -1));
  assert.ok(hostnamePattern.test("project-abc-team.vercel.app"));
  for (const host of ["vercel.app", "project.vercel.app.attacker.test", "-project.vercel.app", "project..vercel.app"]) assert.equal(hostnamePattern.test(host), false);
  // Redis outages cannot be treated as empty data or successful writes.
  store.__test.setKvClient({ get: async () => { throw new Error("offline"); }, set: async () => { throw new Error("offline"); } });
  process.env.NODE_ENV = "production";
  await assert.rejects(() => submissions.createSubmission({ title: "lost" }), { code: "STORAGE_UNAVAILABLE" });
  await assert.rejects(() => store.getDurableValue("submissions:all"), { code: "STORAGE_UNAVAILABLE" });
  console.log("diagnostic fixes passed");
})().catch(error => { console.error(error); process.exitCode = 1; });
