import assert from "node:assert/strict";
import { createEventDataManager } from "../assets/index/modules/event-data-manager.mjs";
const memory = new Map(); const storage = { getItem: (key) => memory.get(key) || null, setItem: (key, value) => memory.set(key, value) };
let calls = 0, resolve; const states = [];
const manager = createEventDataManager({ storage, onState: (state) => states.push(state), fetchEvents: () => { calls += 1; return new Promise((done) => { resolve = done; }); } });
const first = manager.refresh(); const second = manager.refresh();
await Promise.resolve(); assert.equal(calls, 1); resolve([{ id: "real-1", updatedAt: "2026-01-01" }]); await Promise.all([first, second]);
assert.equal(states.at(-1).phase, "success");
const failing = createEventDataManager({ storage, onState: (state) => states.push(state), fetchEvents: async () => { throw new Error("offline"); } });
await failing.refresh(); assert.equal(states.at(-1).cached.events[0].id, "real-1");
const response = { headers: new Headers({ "X-Event-Total": "42" }) };
const metadataManager = createEventDataManager({ storage, onState: state => states.push(state), fetchEvents: async () => ({ events: [{ id: "with-metadata" }], response }) });
assert.deepEqual(await metadataManager.refresh(), [{ id: "with-metadata" }]);
assert.equal(states.at(-1).response, response);
await failing.refresh();
assert.deepEqual(states.at(-1).cached.events, [{ id: "with-metadata" }], "only serializable event data is cached");
console.log("event data manager tests passed");
