const assert = require("assert");
const fs = require("fs");
const http = require("http");
const path = require("path");
const express = require("express");
const { chromium } = require("playwright");

const MAPBOX_STUB = `(() => { class Popup { constructor(){this.h={};} setHTML(v){this.html=v;return this;} setLngLat(){return this;} on(n,f){this.h[n]=f;return this;} addTo(){this.remove();this.el=document.createElement('div');this.el.className='mapboxgl-popup custom-popup';this.el.innerHTML=this.html;document.body.appendChild(this.el);this.h.open?.();return this;} getElement(){return this.el||document.createElement('div');} remove(){this.el?.remove();this.el=null;this.h.close?.();} } class Marker { constructor(o={}){this.el=o.element||document.createElement('div');} setLngLat(v){this.p=v;return this;} setPopup(v){this.popup=v;return this;} addTo(){document.getElementById('map').appendChild(this.el);this.el.addEventListener('click',()=>this.popup?.addTo());return this;} getElement(){return this.el;} remove(){this.el.remove();} } class Map { constructor(){this.h={};this.bounds={west:120,east:122,south:21.5,north:26.5};window.__mapboxTestMap=this;setTimeout(()=>{this.emit('style.load');this.emit('load');},20);} on(n,f){(this.h[n]??=[]).push(f);return this;} emit(n){(this.h[n]||[]).forEach(f=>f({}));} isStyleLoaded(){return true;} getBounds(){return this.bounds;} flyTo(v){this.lastFly=v;this.emit('moveend');} addControl(){} getSource(){return null;} getLayer(){return null;} addSource(){} addLayer(){} setLayoutProperty(){} resize(){} remove(){} } window.mapboxgl={Map,Marker,Popup,NavigationControl:class{}}; })();`;

function startServer(root, events) { const app = express(); app.get('/api/config.js', (_, res) => res.type('js').send('window.APP_CONFIG={};')); app.get('/api/events', (_, res) => res.json(events)); app.get('/api/reaction', (_, res) => res.json({})); app.get('/api/reactions/total', (_, res) => res.json({})); app.use(express.static(root)); return new Promise(resolve => { const server = app.listen(0, '127.0.0.1', () => resolve(server)); }); }
function systemBrowser() { return ["C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe", "C:\\Program Files\\Microsoft\\Edge\\Application\\msedge.exe"].find(fs.existsSync) || ""; }
async function launch() { try { return await chromium.launch({ headless: true }); } catch (error) { return chromium.launch({ headless: true, executablePath: systemBrowser() }); } }
function event(id, hoursAgo, extra = {}) { return { id, title:`事件 ${id} 測試標題`, category:'traffic', city:'台北', lat:25.04, lng:121.56, source:'RSS', content:`這是一則 ${id} 用於瀏覽器驗收的新聞摘要，確認卡片在兩行內閱讀不會溢出。`, publishedAt:new Date(Date.now()-hoursAgo*3600000).toISOString(), locationPrecision:'exact', locationQuality:'high', locationDisplayMode:'point', ...extra }; }

(async () => {
  const root = path.resolve(__dirname, '..');
  const events = [event('h2',2,{url:'https://example.test/original',sourceTrace:[{name:'RSS',title:'來源新聞標題',url:'https://example.test/original'}]}), event('h12',12), event('h30',30), event('d2',48), event('d5',120), event('d10',240), event('estimated',2,{locationPrecision:'district',locationQuality:'medium',locationDisplayMode:'estimated'}), event('city',2,{locationPrecision:'city',locationQuality:'low',locationDisplayMode:'list_only',city:'台南市',lat:23,lng:120}), event('unknown',2,{locationPrecision:'unknown',locationQuality:'low',locationDisplayMode:'list_only',lat:null,lng:null}), event('future',-24,{category:'activity',startsAt:new Date(Date.now()+86400000).toISOString(),publishedAt:new Date(Date.now()).toISOString()})];
  const server = await startServer(root, events); const port = server.address().port; const browser = await launch();
  try {
    const context = await browser.newContext({ viewport:{width:1440,height:900}, geolocation:{latitude:25.04,longitude:121.56}, permissions:['geolocation'] }); const page = await context.newPage(); const errors=[];
    page.on('pageerror', error => errors.push(error.message)); page.on('console', m => { if(m.type()==='error') errors.push(m.text()); });
    await page.addInitScript(() => localStorage.setItem('beta_accepted','true'));
    await page.route('https://api.mapbox.com/mapbox-gl-js/**/mapbox-gl.js', r => r.fulfill({contentType:'application/javascript',body:MAPBOX_STUB}));
    await page.route('https://api.mapbox.com/mapbox-gl-js/**/mapbox-gl.css', r => r.fulfill({contentType:'text/css',body:''})); await page.route(/https:\/\/(fonts|cdnjs)\./, r => r.fulfill({contentType:'text/css',body:''}));
    await page.route('**/_vercel/insights/script.js', r => r.fulfill({contentType:'application/javascript',body:''}));
    await page.goto(`http://127.0.0.1:${port}/`,{waitUntil:'domcontentloaded'}); await page.waitForSelector('.event-card-v2'); console.log('ui e2e: loaded');
    assert.equal(await page.inputValue('#time-range'),'24h'); assert.equal(await page.locator('.event-card-v2').count(),5,'24h excludes old and future events');
    const actionCard = page.locator('.event-card-v2').filter({hasText:'事件 h2'}); const primaryAction = actionCard.locator('.card-action-btn--primary'); const originalAction = actionCard.locator('.card-action-btn--link'); const moreAction = actionCard.locator('.card-action-btn--more');
    assert.equal(await actionCard.locator('.card-source-meta').textContent(),'來源：RSS'); assert.equal(await primaryAction.count(),1); assert.equal(await originalAction.count(),1);
    await originalAction.dispatchEvent('click'); assert.equal(await page.evaluate(()=>window.__mapboxTestMap.lastFly || null),null,'original link does not focus the card');
    await moreAction.click(); assert.equal(await moreAction.getAttribute('aria-expanded'),'true'); await actionCard.locator('[data-action="open-report"]').click(); await page.waitForSelector('#report-modal.visible'); assert.equal(await page.evaluate(()=>window.__mapboxTestMap.lastFly || null),null,'report action does not focus the card'); await page.click('#report-cancel-btn');
    await primaryAction.click(); await page.waitForFunction(()=>Boolean(window.__mapboxTestMap.lastFly)); console.log('ui e2e: default');
    for (const size of [[1440,900],[1280,720],[1024,768]]) { await page.setViewportSize({width:size[0],height:size[1]}); assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,`desktop ${size} has no horizontal scroll`); assert.equal(await page.locator('.map-hero').count(),0); }
    await page.selectOption('#time-range','6h'); await page.waitForTimeout(80); assert.equal(await page.locator('.event-card-v2').count(),4); await page.selectOption('#time-range','3d'); await page.waitForTimeout(80); assert.equal(await page.locator('.event-card-v2').count(),7); await page.selectOption('#time-range','7d'); await page.waitForTimeout(80); assert.equal(await page.locator('.event-card-v2').count(),8);
    await page.selectOption('#time-range','24h'); await page.evaluate(() => { const input = document.getElementById('upcoming-toggle-mobile'); input.checked = true; input.dispatchEvent(new Event('change', { bubbles: true })); }); await page.waitForTimeout(80); assert.equal(await page.locator('.event-card-v2').count(),6,'future layer appears only after explicit toggle'); console.log('ui e2e: filters');
    assert.ok(await page.locator('.marker-location-exact').count()); assert.ok(await page.locator('.marker-location-estimated').count()); assert.ok(await page.locator('.marker-location-city_area').count()); assert.equal(await page.locator('[data-event-id="unknown"].map-pin-svg').count(),0);
    await page.click('#settings-btn'); await page.waitForSelector('#settings-modal.visible'); await page.click('#settings-stats-btn'); await page.waitForFunction(()=>document.body.classList.contains('stats-mode')); await page.click('#settings-btn'); await page.waitForSelector('#settings-modal.visible'); await page.selectOption('#map-mode-select','online'); await page.waitForFunction(()=>document.body.classList.contains('tw-online-mode')); console.log('ui e2e: menu');
    await page.waitForTimeout(1200); const areaState = await page.evaluate(()=>{ window.__mapboxTestMap.emit('moveend'); const button=document.getElementById('search-map-area-btn'); return { hidden: button.hidden, attr: button.hasAttribute('hidden') }; }); console.log('ui e2e: move', areaState); assert.equal(areaState.hidden, false, 'user map movement reveals bounds search'); await page.click('#search-map-area-btn', { force: true }); await page.waitForSelector('#clear-map-area-btn:not([hidden])'); console.log('ui e2e: bounds');
    await page.setViewportSize({width:390,height:844}); await page.evaluate(()=>document.body.classList.remove('stats-mode','tw-online-mode')); await page.reload({waitUntil:'domcontentloaded'}); await page.waitForSelector('.event-card-v2'); console.log('ui e2e: mobile');
    assert.equal(await page.evaluate(()=>document.getElementById('news-sidebar').classList.contains('drawer-collapsed')),true,'mobile starts with a collapsed drawer'); assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'mobile has no horizontal scroll');
    const helpState = await page.evaluate(() => { const button=document.getElementById('map-help-close'); const rect=button.getBoundingClientRect(); return { hidden: button.closest('#map-help-card').hidden, rect:{x:rect.x,y:rect.y,width:rect.width,height:rect.height}, top:document.elementFromPoint(rect.x+2, rect.y+2)?.id || '' }; }); console.log('ui e2e: help', helpState); await page.click('#map-help-close'); console.log('ui e2e: help close', await page.evaluate(() => localStorage.getItem('map_help_dismissed'))); assert.equal(await page.locator('#map-help-card[hidden]').count(),1,'map help is dismissed');
    await page.click('#drawer-handle'); await page.waitForFunction(()=>!document.getElementById('news-sidebar').classList.contains('drawer-collapsed')); console.log('ui e2e: drawer open'); await page.click('.event-card-v2'); await page.waitForFunction(()=>document.getElementById('news-sidebar').classList.contains('drawer-collapsed')); assert.ok(await page.locator('.mapboxgl-popup').count()); console.log('ui e2e: card focus');
    await page.reload({waitUntil:'domcontentloaded'}); await page.waitForSelector('.event-card-v2'); assert.equal(await page.locator('#map-help-card[hidden]').count(),1,'map help dismissal persists');
    for (const size of [[375,667],[360,800]]) { await page.setViewportSize({width:size[0],height:size[1]}); assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,`mobile ${size} has no horizontal scroll`); }
    const relevantErrors = errors.filter(message => !/Failed to load resource/.test(message)); assert.deepEqual(relevantErrors,[],'no unhandled browser errors: '+relevantErrors.join(' | ')); await context.close(); console.log('news map UI e2e tests passed');
  } finally { await browser.close(); server.close(); }
})().catch(error => { console.error(error); process.exit(1); });
